### ISSUE TITLE
OverFlow error

### ISSUE THREAD

**Issue by mpiffari** [hahnicity/ucdpv_pva_ml#1]
Hi @hahnicity ,
I'm trying to check out the result of your work on PVA classification, after you and Jason shared with me the dataset.

But I'm getting this problem on ventMAP library:

$ ./experiments.sh
Traceback (most recent call last):
  File "learn.py", line 19, in <module>
    from collate import (
  File "[...]\ucdpv_pva_ml\ucdpv_pva_ml-master\analytics\collate.py", line 10, in <module>
    from ventmap.breath_meta import get_file_experimental_breath_meta
  File "[...]\anaconda3\envs\APL\lib\site-packages\ventmap\breath_meta.py", line 20, in <module>
    from ventmap.raw_utils import extract_raw
  File "[...]\anaconda3\envs\APL\lib\site-packages\ventmap\raw_utils.py", line 25, in <module>
    csv.field_size_limit(sys.maxsize)
OverflowError: Python int too large to convert to C long

I found this possible solution (https://stackoverflow.com/questions/38314118/overflowerror-python-int-too-large-to-convert-to-c-long-on-windows-but-not-ma).

**Comment by hahnicity** [comment]
Looks like a problem being caused by an old version of ventMAP. 

Can you do this

`pip install -U ventmap`

And then try re-running the script?

**Comment by mpiffari** [comment]
Hi @hahnicity ,
the previous problem appears to be solved

I come with another one, that is a index out of range problem:
Traceback (most recent call last):
  File "learn.py", line 662, in <module>
    main()
  File "learn.py", line 553, in main
    feature_func, args.bins, args.pickle_file, args.new_pickling_file, gold_stnd_func, args.new_csv_file
  File "learn.py", line 124, in get_x_y
    df = feature_func(bins, gold_stnd_func)
  File "[...]\ucdpv_pva_ml\ucdpv_pva_ml-master\analytics\collate.py", line 706, in get_settings_and_derived_features
    return do_basket_function(0, _vent_and_derived_func, gold_stnd_func)
  File "[...]\ucdpv_pva_ml\ucdpv_pva_ml-master\analytics\collate.py", line 221, in do_basket_function
    observations, files, target_vector = gold_stnd_func()
  File "[...]\ucdpv_pva_ml\ucdpv_pva_ml-master\analytics\collate.py", line 204, in get_binary_target_deriv_valid_dbl_trigger_data
    return _get_binary_target_async_data(DERIVATION_VALIDATION_COHORT_DIRS, 'dbl')
  File "[...]\ucdpv_pva_ml\ucdpv_pva_ml-master\analytics\collate.py", line 79, in _get_binary_target_async_data
    observations = get_y_observations(cohort_dirs)
  File "[...]\ucdpv_pva_ml\ucdpv_pva_ml-master\analytics\collate.py", line 55, in get_y_observations
    df = do_file(files[0])
  File "[...]\ucdpv_pva_ml\ucdpv_pva_ml-master\analytics\collate.py", line 47, in do_file
    patient = file.split("/")[-2]
IndexError: list index out of range
